In [1]:
def norm_feature(data):
    n_max = max(data)
    n_min = min(data)
    l_data = len(data)
 
    for i in range(0,l_data):
        data[i] = (data[i] -n_min) / (n_max - n_min)

    return data

In [2]:
data = [10, 25, 15, 30, 50]

n_data = norm_feature(data)
n_data 

[0.0, 0.375, 0.125, 0.5, 1.0]

In [3]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [4]:
data = [
    [100, 0.01],
    [8, 0.05],
    [50, 0.005],
]

np_data = np.asarray(data)
mm_scaler = MinMaxScaler()
mm_data = mm_scaler.fit_transform(data)
mm_data

array([[1.        , 0.11111111],
       [0.        , 1.        ],
       [0.45652174, 0.        ]])

In [5]:
from statistics import mean,stdev

def std_feature(data):
    baris_data = data.shape[0]
    kolom_data = data.shape[1]

    for i in range(0, baris_data):
        for j in range(0, kolom_data):
            data[i][j] = (data[i,j] - mean(data[:, j])) / stdev(data[:,j])

    return data


In [6]:
data = [
    [100, 0.001],
    [8, 0.05],
    [50, 0.005],
    [88, 0.07],
    [4, 0.1]
]

data = np.array(data)
std_data = std_feature(data)
std_data

array([[ 1.13053908, -1.04102352],
       [-0.58585228,  0.43340554],
       [ 0.54596936,  0.16378374],
       [ 1.78715622,  0.2189989 ],
       [ 1.53764773,  0.21485145]])

In [7]:
from sklearn.preprocessing import StandardScaler

ss_scaler = StandardScaler()

std_data = ss_scaler.fit_transform(data)
print(std_data)

[[ 0.29249575 -1.96885878]
 [-1.73637127  0.8250468 ]
 [-0.39849714  0.31413861]
 [ 1.06865257  0.4187662 ]
 [ 0.77372009  0.41090717]]


In [22]:
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

data = [
    ["POLINEMA"],
    ["PENS"],
    ["PNJ"],
    ["PNP"],
    ["POLBAN"]
]

encoder = OrdinalEncoder()
ord_oe = encoder.fit_transform(data)

print(ord_oe)


[[4.]
 [0.]
 [1.]
 [2.]
 [3.]]


In [23]:
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

data = [
    ["POLINEMA"],
    ["PENS"],
    ["PNJ"],
    ["PNP"],
    ["POLBAN"]
]

encoder = OneHotEncoder(sparse=False)
ord_oe = encoder.fit_transform(data)

print(ord_oe)


[[0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [56]:
from sklearn.feature_extraction.text import TfidfVectorizer

corpus = [
    'the house had a tiny little mouse',
    'the cat saw the mouse',
    'the mouse ran away from the house',
    'the cat finally ate the mouse',
    'the end of the mouse story'
]

print(vectorizer.get_feature_names_out())
print(data.toarray())


['ate' 'away' 'cat' 'end' 'finally' 'house' 'little' 'mouse' 'ran' 'saw'
 'story' 'tiny']
[[0.         0.         0.         0.         0.         0.4755751
  0.58946308 0.28088232 0.         0.         0.         0.58946308]
 [0.         0.         0.58873218 0.         0.         0.
  0.         0.34771471 0.         0.72971837 0.         0.        ]
 [0.         0.58946308 0.         0.         0.         0.4755751
  0.         0.28088232 0.58946308 0.         0.         0.        ]
 [0.58946308 0.         0.4755751  0.         0.58946308 0.
  0.         0.28088232 0.         0.         0.         0.        ]
 [0.         0.         0.         0.67009179 0.         0.
  0.         0.31930233 0.         0.         0.67009179 0.        ]]
